# Generated by Django 3.2.7 on 2021-09-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Nombres'),
        ),
    ]
